[functionalities]
[functionalities.managing_python]
name = "Managing Python installations"
description = "Installs multiple versions of Python, and provides ways to switch between them on a global or per-project basis."
[functionalities.creating_virtual_envs]
name = "Creating a virtual environment"
description = "Can create a virtual environment, i.e., a specific Python interpreter and an isolated set of installed Python packages. Typically, a Python project uses at least one virtual environment. This may be a standalone virtual environment stored in a central location, or it may be inside a project directory and tied to that project. There are two kinds of virtual environments relevant to Python development: regular Python virtual environments; and Conda environments which can include other non-Python software packages."
[functionalities.managing_dependencies]
name = "Managing dependencies"
description = "Provides a way to declare project dependencies and install them into a virtual environment."
[functionalities.managing_virtual_envs]
name = "Managing multiple virtual environments"
description = "Manages multiple virtual environments for a single project at once, such as for testing. This includes creating the virtual environment, declaring and installing dependencies, and tearing them down. Such tools often let one create virtual environments from a matrix of parameters."
[functionalities.writing_lockfiles]
name = "Writing lockfiles"
description = "Lockfiles specify the exact set of packages installed in an environment with exact versions. They allow for reproducing that environment."
[functionalities.building_packages]
name = "Building packages"
description = "Creating file archives of Python code that can be distributed and installed by other users. There are two kinds of packages common for Python: regular Python packages distributed on PyPI, and conda packages "
[functionalities.publishing_packages]
name = "Publishing packages"
description = "Publishing Python packages to PyPI or conda packages to conda-forge."

[[tools]]
name = "pyenv"
description = "FILL ME IN"
[[tools.functionalities.managing_python]]
explanation = "FILL ME IN"
reference = "https://github.com/pyenv/pyenv#what-pyenv-does"

[[tools]]
name = "asdf"
description = "FILL ME IN"
[[tools.functionalities.managing_python]]
explanation = "FILL ME IN"
reference = "https://github.com/asdf-community/asdf-python"

[[tools]]
name = "rtx"
description = "FILL ME IN"
[[tools.functionalities.managing_python]]
explanation = "FILL ME IN"
reference = "https://github.com/jdx/rtx/blob/main/docs/python.md"

[[tools]]
name = "conda"
description = "FILL ME IN"
[[tools.functionalities.managing_python]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
[[tools.functionalities.creating_virtual_envs]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "conda"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "python"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "conda"

[[tools]]
name = "mamba"
description = "FILL ME IN"
[[tools.functionalities.managing_python]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
[[tools.functionalities.creating_virtual_envs]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "conda"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "python"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "conda"

[[tools]]
name = "venv"
description = "FILL ME IN"
[[tools.functionalities.creating_virtual_envs]]
explanation = "FILL ME IN"
reference = "https://docs.python.org/3/library/venv.html#creating-virtual-environments"
icon = "python"

[[tools]]
name = "virtualenv"
description = "FILL ME IN"
[[tools.functionalities.creating_virtual_envs]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "python"

[[tools]]
name = "Pip"
description = "FILL ME IN"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "python"

[[tools]]
name = "Tox"
description = "FILL ME IN"
[[tools.functionalities.managing_virtual_envs]]
explanation = "FILL ME IN"
reference = "FILL ME IN"

[[tools]]
name = "Nox"
description = "FILL ME IN"
[[tools.functionalities.managing_virtual_envs]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "python"
[[tools.functionalities.managing_virtual_envs]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "conda"

[[tools]]
name = "Pipenv"
description = "FILL ME IN"
[[tools.functionalities.creating_virtual_envs]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "python"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "python"

[[tools]]
name = "Hatch"
description = "FILL ME IN"
[[tools.functionalities.creating_virtual_envs]]
explanation = "FILL ME IN"
reference = "https://hatch.pypa.io/latest/environment/#creation"
icon = "python"
[[tools.functionalities.managing_virtual_envs]]
explanation = "FILL ME IN"
reference = "https://hatch.pypa.io/latest/environment/"
icon = "python"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "python"
[[tools.functionalities.building_packages]]
explanation = "FILL ME IN"
reference = "https://hatch.pypa.io/latest/build/"
icon = "python"
[[tools.functionalities.publishing_packages]]
explanation = "FILL ME IN"
reference = "https://hatch.pypa.io/latest/publish/"
icon = "python"

[[tools]]
name = "Poetry"
description = "FILL ME IN"
[[tools.functionalities.creating_virtual_envs]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "python"
[[tools.functionalities.managing_virtual_envs]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "python"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "python"
[[tools.functionalities.building_packages]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
icon = "python"

[[tools]]
name = "PDM"
description = "FILL ME IN"
[[tools.functionalities.creating_virtual_envs]]
explanation = "FILL ME IN"
reference = "https://pdm.fming.dev/latest/usage/venv/"
[[tools.functionalities.managing_virtual_envs]]
explanation = "FILL ME IN"
reference = "https://pdm.fming.dev/latest/usage/venv/"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "https://pdm.fming.dev/latest/usage/dependency/"
[[tools.functionalities.building_packages]]
explanation = "FILL ME IN"
reference = "https://pdm.fming.dev/latest/usage/publish/"

[[tools]]
name = "Rye"
description = "FILL ME IN"
[[tools.functionalities.managing_python]]
explanation = "FILL ME IN"
reference = "https://github.com/mitsuhiko/rye#some-of-the-things-it-does"
[[tools.functionalities.creating_virtual_envs]]
explanation = "FILL ME IN"
reference = "https://rye-up.com/guide/basics/#first-sync"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "https://rye-up.com/guide/basics/#adding-dependencies"
[[tools.functionalities.writing_lockfiles]]
explanation = "FILL ME IN"
reference = "https://rye-up.com/guide/sync/"
[[tools.functionalities.building_packages]]
explanation = "Rye provides a `build` command to build packages, which uses build under the hood."
reference = "hhttps://rye-up.com/guide/publish/"
[[tools.functionalities.publishing_packages]]
explanation = "Rye provides a `publish` command to publish to PyPI, which uses twine under the hood."
reference = "https://rye-up.com/guide/publish/"

[[tools]]
name = "pip-compile"
description = "FILL ME IN"
[[tools.functionalities.writing_lockfiles]]
explanation = "FILL ME IN"
reference = "FILL ME IN"

[[tools]]
name = "conda-lock"
description = "FILL ME IN"
[[tools.functionalities.writing_lockfiles]]
explanation = "FILL ME IN"
reference = "FILL ME IN"

[[tools]]
name = "Build"
description = "FILL ME IN"
[[tools.functionalities.building_packages]]
explanation = "FILL ME IN"
reference = "https://pypa-build.readthedocs.io/en/stable/index.html"

[[tools]]
name = "Twine"
description = "FILL ME IN"
[[tools.functionalities.publishing_packages]]
explanation = "FILL ME IN"
reference = "https://twine.readthedocs.io/en/stable/"

[[tools]]
name = "Flit"
description = "FILL ME IN"
[[tools.functionalities.building_packages]]
explanation = "FILL ME IN"
reference = "FILL ME IN"
