[meta]
site_url = "https://jayqi.github.io/python-tools-reference/"

[sections]
[sections.python_vs_conda]
text = """
    **Python packages** are distributable archives of Python code. Even if a Python package
    includes code in another language, like C++ or Rust, the package would have Python "bindings"
    that allow that code to be called from Python. **Virtual environments** are isolated and
    independent sets of installed software, and it's a best practice to have a virtual environment
    per project. **Python environments** then refers to virtual environments for Python packages.

    On the other hand, **Conda packages** are distributable archives of software in any language.
    They could include Python libraries, but system libraries, R libraries, Julia libraries, and
    other executable programs are also often distributed as Conda packages. **Conda environments**
    are accordingly virtual environments for Conda packages. However, Python has a special level of
    support in the Conda ecosystem, and you can actually use
    [pip to install Python packages](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html)
    into a Conda environment as if it were a Python virtual environment. Those Python packages will
    be available in the Conda environment alongside any Conda packages.

    **Which kind of package ecosystem should you use?** If you are working with exclusively Python
    packages, you will likely have a better experience using Python virtual environments and Python
    package tools. The experience will be simpler, and you'll be able to install packages more
    quickly and easily. However, if you are likely to need software in other languages, or if your
    Python dependencies have dependencies on system-level libraries (e.g., scientific computing and
    deep learning frameworks often depend on system-level linear algebra libraries), then Conda
    can be useful for handling it all.
"""

[functionalities]
[functionalities.managing_python]
name = "Managing Python installations"
description = """
    Installs multiple versions of Python, and provides ways to switch between them on a global or
    per-project basis.
"""
[functionalities.creating_a_virtual_env]
name = "Creating a virtual environment"
description = """
    Can create a virtual environment, i.e., a specific Python interpreter and an isolated set of
    installed Python packages. Typically, a Python project uses at least one virtual environment.
    This may be a standalone virtual environment stored in a central location, or it may be inside
    a project directory and tied to that project. There are two kinds of virtual environments
    relevant to Python development: regular Python virtual environments; and Conda environments
    which can include other non-Python software packages.
"""
[functionalities.managing_dependencies]
name = "Managing dependencies"
description = """
    Provides a way to declare project dependencies and install them into a virtual environment.
"""
[functionalities.automating_virtual_envs]
name = "Automation of multiple virtual environments"
description = """
    Automation for the creation, dependency management, and command invocation of multiple virtual
    environments for a single project. This is often used to manage separate environments for
    tests, documentation generation, and linting. Such tools often let one create virtual
    environments from a matrix of parameters.
"""
[functionalities.writing_lock_files]
name = "Writing lock files"
description = """
    Lock files specify the exact set of packages installed in an environment with exact versions.
    They allow for reproducing that environment.
"""
[functionalities.building_packages]
name = "Building packages"
description = """
    Creating file archives of Python code that can be distributed and installed by other users.
    There are two kinds of packages common for Python: regular Python packages distributed on PyPI,
    and conda packages.
"""
[functionalities.publishing_packages]
name = "Publishing packages"
description = """
    Publishing Python packages to PyPI or conda packages to conda-forge.
"""

[[tools]]
name = "pyenv"
website = "https://github.com/pyenv/pyenv"
github = "pyenv/pyenv"
description = """
    pyenv is a tool that installs multiple versions of Python and lets you switch between them.
"""
[[tools.functionalities.managing_python]]
explanation = """
    pyenv has an `install` command for installing Python versions, a `global` command for setting
    a global Python version, and a `local` command for setting a per-project Python version.
"""
reference = "https://github.com/pyenv/pyenv#what-pyenv-does"

[[tools]]
name = "asdf"
github = "asdf-vm/asdf"
website = "https://asdf-vm.com/"
description = """
    asdf is a tool for managing multiple versions of many language runtimes. It supports managing
    Python through the asdf-python plugin.
"""
[[tools.functionalities.managing_python]]
explanation = """
    asdf with the asdf-python plugin has an `install python` command for installing Python
    versions, a `global python` command for setting a global Python version, and a `local python`
    command for setting a per-project Python version.
"""
reference = "https://github.com/asdf-community/asdf-python"

[[tools]]
name = "rtx"
github = "jdx/rtx"
website = "https://github.com/jdx/rtx"
description = """
    rtx is a tool for managing multiple versions of many language runtimes, including Python. It
    started out as a clone of asdf implemented in Rust.
"""
[[tools.functionalities.managing_python]]
explanation = """
    rtx has an `install python@<version>` command for installing Python versions and a
    `use python@<version>` command for setting an active Python version.
"""
reference = "https://github.com/jdx/rtx/blob/main/docs/python.md"

[[tools]]
name = "conda"
github = "conda/conda"
website = "https://docs.conda.io/en/latest/"
description = "FILL ME IN"
[[tools.functionalities.managing_python]]
explanation = "FILL ME IN"
reference = "https://docs.conda.io/projects/conda/en/stable/user-guide/getting-started.html#managing-python"
[[tools.functionalities.creating_a_virtual_env]]
explanation = "FILL ME IN"
reference = "https://docs.conda.io/projects/conda/en/stable/user-guide/getting-started.html#managing-envs"
icon = "conda"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "https://docs.conda.io/projects/conda/en/stable/user-guide/getting-started.html#managing-pkgs"
icon = "python"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "https://docs.conda.io/projects/conda/en/stable/user-guide/getting-started.html#managing-pkgs"
icon = "conda"

[[tools]]
name = "mamba"
github = "mamba-org/mamba"
website = "https://mamba.readthedocs.io/en/stable/"
description = "FILL ME IN"
[[tools.functionalities.managing_python]]
explanation = "FILL ME IN"
reference = "https://mamba.readthedocs.io/en/latest/user_guide/mamba.html#quickstart"
[[tools.functionalities.creating_a_virtual_env]]
explanation = "FILL ME IN"
reference = "https://mamba.readthedocs.io/en/latest/user_guide/mamba.html#quickstart"
icon = "conda"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "https://mamba.readthedocs.io/en/latest/user_guide/mamba.html#quickstart"
icon = "python"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "https://mamba.readthedocs.io/en/latest/user_guide/mamba.html#quickstart"
icon = "conda"

[[tools]]
name = "venv"
website = "https://docs.python.org/3/library/venv.html"
description = "A Python standard library module for creating virtual environments."
[[tools.functionalities.creating_a_virtual_env]]
explanation = "FILL ME IN"
reference = "https://docs.python.org/3/library/venv.html#creating-virtual-environments"
icon = "python"

[[tools]]
name = "virtualenv"
github = "pypa/virtualenv"
website = "https://virtualenv.pypa.io/en/latest/"
description = "FILL ME IN"
[[tools.functionalities.creating_a_virtual_env]]
explanation = "FILL ME IN"
reference = "https://virtualenv.pypa.io/en/latest/user_guide.html"
icon = "python"

[[tools]]
name = "Pip"
github = "pypa/pip"
website = "https://pip.pypa.io/en/stable/"
description = "FILL ME IN"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "https://pip.pypa.io/en/stable/getting-started/"
icon = "python"

[[tools]]
name = "tox"
github = "tox-dev/tox"
website = "https://tox.wiki/en/stable/"
description = "FILL ME IN"
[[tools.functionalities.automating_virtual_envs]]
explanation = "FILL ME IN"
reference = "https://tox.wiki/en/4.11.3/user_guide.html"

[[tools]]
name = "Nox"
github = "wntrblm/nox"
website = "https://nox.thea.codes/en/stable/"
description = "FILL ME IN"
[[tools.functionalities.automating_virtual_envs]]
explanation = "FILL ME IN"
reference = "https://nox.thea.codes/en/stable/config.html#defining-sessions"
icon = "python"
[[tools.functionalities.automating_virtual_envs]]
explanation = "FILL ME IN"
reference = "https://nox.thea.codes/en/stable/config.html#configuring-a-session-s-virtualenv"
icon = "conda"

[[tools]]
name = "Pipenv"
github = "pypa/pipenv"
website = "https://pipenv.pypa.io/en/stable/"
description = "FILL ME IN"
[[tools.functionalities.creating_a_virtual_env]]
explanation = "FILL ME IN"
reference = "https://pipenv.pypa.io/en/latest/installation/#virtualenv-mapping-caveat"
icon = "python"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "https://pipenv.pypa.io/en/stable/installation/#installing-packages-for-your-project"
icon = "python"
[[tools.functionalities.writing_lock_files]]
explanation = "FILL ME IN"
reference = "https://pipenv.pypa.io/en/stable/installation/#installing-packages-for-your-project"
icon = "python"

[[tools]]
name = "Hatch"
github = "pypa/hatch"
website = "https://hatch.pypa.io/latest/"
description = "FILL ME IN"
[[tools.functionalities.creating_a_virtual_env]]
explanation = "FILL ME IN"
reference = "https://hatch.pypa.io/latest/environment/#creation"
icon = "python"
[[tools.functionalities.automating_virtual_envs]]
explanation = "FILL ME IN"
reference = "https://hatch.pypa.io/latest/environment/"
icon = "python"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "https://hatch.pypa.io/latest/environment/#dependencies"
icon = "python"
[[tools.functionalities.building_packages]]
explanation = "FILL ME IN"
reference = "https://hatch.pypa.io/latest/build/"
icon = "python"
[[tools.functionalities.publishing_packages]]
explanation = "FILL ME IN"
reference = "https://hatch.pypa.io/latest/publish/"
icon = "python"

[[tools]]
name = "Poetry"
github = "python-poetry/poetry"
website = "https://python-poetry.org/"
description = "FILL ME IN"
[[tools.functionalities.creating_a_virtual_env]]
explanation = "FILL ME IN"
reference = "https://python-poetry.org/docs/basic-usage/#using-your-virtual-environment"
icon = "python"
[[tools.functionalities.automating_virtual_envs]]
explanation = "FILL ME IN"
reference = "https://python-poetry.org/docs/managing-environments/"
icon = "python"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "https://python-poetry.org/docs/basic-usage/#specifying-dependencies"
icon = "python"
[[tools.functionalities.writing_lock_files]]
explanation = "FILL ME IN"
reference = "https://python-poetry.org/docs/basic-usage/#installing-without-poetrylock"
[[tools.functionalities.building_packages]]
explanation = "FILL ME IN"
reference = "https://python-poetry.org/docs/libraries/#packaging"
icon = "python"
[[tools.functionalities.publishing_packages]]
explanation = "FILL ME IN"
reference = "https://python-poetry.org/docs/libraries/#publishing-to-pypi"
icon = "python"

[[tools]]
name = "PDM"
github = "pdm-project/pdm"
website = "https://pdm.fming.dev/latest/"
description = "FILL ME IN"
[[tools.functionalities.creating_a_virtual_env]]
explanation = "FILL ME IN"
reference = "https://pdm.fming.dev/latest/usage/venv/"
[[tools.functionalities.automating_virtual_envs]]
explanation = "FILL ME IN"
reference = "https://pdm.fming.dev/latest/usage/venv/"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "https://pdm.fming.dev/latest/usage/dependency/"
[[tools.functionalities.building_packages]]
explanation = "FILL ME IN"
reference = "https://pdm.fming.dev/latest/usage/publish/"

[[tools]]
name = "Rye"
github = "mitsuhiko/rye"
website = "https://rye-up.com/"
description = "FILL ME IN"
[[tools.functionalities.managing_python]]
explanation = "FILL ME IN"
reference = "https://github.com/mitsuhiko/rye#some-of-the-things-it-does"
[[tools.functionalities.creating_a_virtual_env]]
explanation = "FILL ME IN"
reference = "https://rye-up.com/guide/basics/#first-sync"
[[tools.functionalities.managing_dependencies]]
explanation = "FILL ME IN"
reference = "https://rye-up.com/guide/basics/#adding-dependencies"
[[tools.functionalities.writing_lock_files]]
explanation = "FILL ME IN"
reference = "https://rye-up.com/guide/sync/"
[[tools.functionalities.building_packages]]
explanation = "Rye provides a `build` command to build packages, which uses build under the hood."
reference = "https://rye-up.com/guide/publish/"
[[tools.functionalities.publishing_packages]]
explanation = "Rye provides a `publish` command to publish to PyPI, which uses twine under the hood."
reference = "https://rye-up.com/guide/publish/"

[[tools]]
name = "pip-tools"
github = "jazzband/pip-tools"
website = "https://github.com/jazzband/pip-tools/"
description = "FILL ME IN"
[[tools.functionalities.writing_lock_files]]
explanation = "FILL ME IN"
reference = "https://github.com/jazzband/pip-tools/#example-usage-for-pip-compile"

[[tools]]
name = "conda-lock"
github = "conda/conda-lock"
website = "https://github.com/conda/conda-lock"
description = "FILL ME IN"
[[tools.functionalities.writing_lock_files]]
explanation = "FILL ME IN"
reference = "https://github.com/conda/conda-lock#basic-usage"

[[tools]]
name = "Build"
github = "pypa/build"
website = "https://pypa-build.readthedocs.io/en/stable/"
description = "FILL ME IN"
[[tools.functionalities.building_packages]]
explanation = "FILL ME IN"
reference = "https://pypa-build.readthedocs.io/en/stable/index.html"

[[tools]]
name = "Twine"
github = "pypa/twine"
website = "https://twine.readthedocs.io/en/stable/"
description = "FILL ME IN"
[[tools.functionalities.publishing_packages]]
explanation = "FILL ME IN"
reference = "https://twine.readthedocs.io/en/stable/"

[[tools]]
name = "Flit"
github = "pypa/flit"
website = "https://flit.pypa.io/en/stable/"
description = "FILL ME IN"
[[tools.functionalities.building_packages]]
explanation = "FILL ME IN"
reference = "https://flit.pypa.io/en/stable/index.html#usage"
[[tools.functionalities.publishing_packages]]
explanation = "FILL ME IN"
reference = "https://flit.pypa.io/en/stable/upload.html"
